name: Continuous Integration - API de Entregas

on:
  push:
    branches: ["master"] # Alterado para master
  pull_request:
    branches: ["master"] # Alterado para master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: zip, json, mbstring
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          if ! grep -q "phpunit/phpunit" composer.json; then
            composer require --dev phpunit/phpunit ^9
          fi

      - name: Start PHP server
        run: php -S localhost:8000 -t . > /dev/null 2>&1 &
        background: true

      - name: Run tests
        run: ./vendor/bin/phpunit tests/
