name: Continuous Integration - API de Entregas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuração do ambiente PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: zip, json, mbstring
          tools: composer:v2
          coverage: none

      # 3. Instalação de dependências
      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
          # Instala o PHPUnit se não estiver no composer.json
          if ! grep -q "phpunit/phpunit" composer.json; then
            composer require --dev phpunit/phpunit ^9
          fi

      # 4. Inicia o servidor PHP para testes
      - name: Start PHP server
        run: php -S localhost:8090 -t . > /dev/null 2>&1 &
        background: true

      # 5. Execução dos testes
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests/
